kind: Deployment
apiVersion: apps/v1
metadata:
  name: shipping-service
  labels:
    app: shipping-service
    app.kubernetes.io/component: shipping-service
    app.kubernetes.io/instance: pipeline-test
    app.kubernetes.io/part-of: Microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
      deploymentconfig: shipping-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: shipping-service
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: shipping-service
          image: image-registry.openshift-image-registry.svc:5000/pipeline-test/shipping-service@sha256:bd3e3b701b6fec249cc8292fba8ff8dc7e5f128614b1d750d779fdccc2272df7
          ports:
            - name: jolokia
              containerPort: 8778
              protocol: TCP
            - containerPort: 9779
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      tolerations: 
        - key: node.network-zone-type/operations-zone
          operator: Equal
          value: 'true'
          effect: NoSchedule      
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
